server:
  port: 8080

logging:
  level:
    root: INFO
    '[org.springframework.http]': TRACE
    '[org.springframework.web]': TRACE
    '[org.springframework.security]': TRACE
    '[org.springframework.security.oauth2]': TRACE

spring:
  messages:
    basename: i18n/messages
  thymeleaf:
    cache: false
 